name: pytorch
dependencies:
  - python=3.8
  - dask
  - matplotlib-base
  - numpy
  - pandas
  - panel 
  - pytables
  - scipy
  - scikit-image
  - scikit-learn
  - seaborn
  - statsmodels
  - xarray
    # Jupyter and Airflow framework specific librairie
  - jupyter
  - jupyterhub
  - jupyterlab
  - appmode
  - notebook
  - ipywidgets
  - ipyleaflet
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - papermill
  - psycopg2
  - cloudpickle
    # EO / Weather specific
  - bokeh
  - bottleneck
  - cartopy
  - cmocean
  - descartes
  - geos
  - geopandas
  - iris
  - iris-grib
    # metpy
    # metview-batch
  - magics
  - netcdf4
  - protobuf
  - pynio
  - shapely
  - siphon
  - pip
  - pip:
    - -r file:requirements-jupyter-airflow.txt